//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberBio
    {
        public int MemberBioID { get; set; }
        public int UserID { get; set; }
        public string BioText { get; set; }
        public string ExtraText { get; set; }
        public string MusicalInfluences { get; set; }
        public string PictureURL { get; set; }
        public string VoicePart { get; set; }
    
        public virtual User User { get; set; }
    }
}
