//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Performance
    {
        public int PerformanceID { get; set; }
        public string PerformanceName { get; set; }

        [DisplayFormat(DataFormatString="{0:MM/dd/yyyy}", ApplyFormatInEditMode=true)]
        public System.DateTime PerformanceDate { get; set; }
        public string PerformanceTime { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
    }
}
