//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repertoire
    {
        public int RepertoireID { get; set; }
        public string SongTitle { get; set; }
        public string OriginalArtist { get; set; }
        public string Soloist { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool Retired { get; set; }
    }
}
