//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catch22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContent
    {
        public int SiteContentID { get; set; }
        public string ContentTitle { get; set; }
        public string ContentText { get; set; }
    }
}
